image: mcr.microsoft.com/dotnet/core/sdk:3.1.100

stages:
    - test
    - deploy
    - documentation

release:
    stage: deploy
    only:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        paths:
          - ./*.nupkg
    script:
        - ./build.sh --configuration=Release --buildnumber=$CI_PIPELINE_IID
        - dotnet nuget push DotGGPK*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json

debug:
    stage: test
    script:
        - ./build.sh
    coverage: /Total\s+\|\s+\d+\D\d+\%/
    artifacts:
        reports:
            junit:
                - './src/**/TestResults/TestResults.xml'


pages:
  stage: documentation
  only:
  - tags
  artifacts:
    paths:
    - public
  script:
  - ./build.sh --configuration=Release