image: mcr.microsoft.com/dotnet/core/sdk:3.1.100

stages:
    - test
    - deploy
    - documentation

cache:
  paths:
  - .cache/

release:
    stage: deploy
    only:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        paths:
          - ./*.nupkg
    script:
        - ./build.sh --configuration=Release
        - dotnet nuget push DotGGPK*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json --no-symbols 1

debug:
    stage: test
    script:
        - ./build.sh
    coverage: Total\s+\|\s+\d+\D\d+\%

pages:
  stage: documentation
  only:
  - tags
  artifacts:
    paths:
    - public
  script:
  - ./build.sh --configuration=Release