stages:
    - test
    - deploy

cache:
  paths:
  - .cache/

before_script:
    - dotnet tool install --global Cake.Tool --version 0.31.0 
    - dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.0.4

release:
    stage: deploy
    only:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        paths:
          - ./*.nupkg
    script:
        - dotnet-cake --configuration=Release
        - dotnet nuget push DotGGPK*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json

debug:
    stage: test
    script:
        - dotnet-cake