stages:
    - test
    - deploy

cache:
  paths:
  - .cache/

release:
    stage: deploy
    only:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        paths:
          - ./*.nupkg
    script:
        - ./build --configuration=Release
        - dotnet nuget push DotGGPK*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json

debug:
    stage: test
    script:
        - ./build